# .scrutinizer.yml
build:
  environment:
    php:
      version: '7.3.3'
  dependencies:
    after:
      - git clone --depth=1 https://github.com/XOOPS/XoopsCore
  project_setup:
    override: true
  tests:
    override:
      - php-scrutinizer-run --enable-security-analysis
filter:
  excluded_paths:
    - "tests/*"
  dependency_paths:
    - XoopsCore/*
tools:
  external_code_coverage:
    timeout: 1800   # Timeout in seconds.
    runs: 1         # Scrutinizer will wait for n code coverage submissions
