language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - 

install:
  - 

before_script:
  - mysql -e 'create database'
  - php console/console.php ci-bootstrap
  - php console/console.php ci-install

script:
  - 

after_script:
  - 